package travelcare_agent.dryrun;

public enum SideEffectOperation {
    SESSION_WRITE, SESSION_EVENT_WRITE, WORKFLOW_WRITE, WORKFLOW_STEP_WRITE, TOOL_CALL_WRITE,
    IDEMPOTENCY_WRITE, AUDIT_WRITE, HUMAN_REVIEW_WRITE, WORKFLOW_TASK_WRITE, RABBITMQ_PUBLISH,
    AGENT_RUN_WRITE, EXTERNAL_PROVIDER_CALL, EXTERNAL_ADAPTER_CALL, NOTIFICATION_SEND, REFUND_CASE_WRITE
}
