CREATE TABLE IF NOT EXISTS agent_runs (
    id BIGINT PRIMARY KEY,
    session_id BIGINT NOT NULL,
    workflow_id BIGINT NULL,
    task_id BIGINT NULL,
    correlation_id VARCHAR(128) NULL,
    run_type VARCHAR(32) NOT NULL,
    source VARCHAR(64) NOT NULL,
    input_event_ids_json TEXT NOT NULL,
    retrieval_chunk_ids_json TEXT NOT NULL,
    memory_ids_json TEXT NOT NULL,
    workflow_snapshot_json TEXT NULL,
    prompt_version VARCHAR(64) NOT NULL,
    response_template_version VARCHAR(64) NOT NULL,
    context_hash VARCHAR(128) NULL,
    context_snapshot_hash VARCHAR(128) NULL,
    answer_hash VARCHAR(128) NULL,
    output_event_id BIGINT NULL,
    status VARCHAR(32) NOT NULL,
    latency_ms BIGINT NULL,
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(512) NULL,
    created_by VARCHAR(64) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_agent_runs_session_created (session_id, created_at),
    INDEX idx_agent_runs_workflow_created (workflow_id, created_at),
    INDEX idx_agent_runs_task (task_id),
    INDEX idx_agent_runs_output_event (output_event_id),
    INDEX idx_agent_runs_correlation (correlation_id),
    INDEX idx_agent_runs_status_created (status, created_at)
);
