package travelcare_agent.evidence;

public enum RiskWarning {
    TRACE_EVIDENCE_UNAVAILABLE,
    TRACE_SNAPSHOT_CORRUPTED,
    ANSWERABILITY_UNKNOWN,
    CITATION_EVIDENCE_UNAVAILABLE,
    SUPPLIER_EVIDENCE_UNAVAILABLE,
    REFUND_DECISION_UNVERIFIED,
    TRANSCRIPT_NOT_AUTHORITATIVE,
    MANUAL_REFUND_REQUIRES_VERIFICATION
}
