package travelcare_agent.trace;

public enum SpanType {
    REQUEST, CONTEXT, RETRIEVAL, MODEL, WORKFLOW, WORKFLOW_STEP, TOOL, POLICY,
    ASYNC_TASK, HUMAN_REVIEW, AUDIT, OUTPUT, FALLBACK, TIMEOUT, GUARDRAIL
}
