package travelcare_agent.trace;

import org.slf4j.Logger; import org.slf4j.LoggerFactory; import org.springframework.stereotype.Service;
import travelcare_agent.trace.entity.*;
import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.time.Duration; import java.time.LocalDateTime; import java.util.HexFormat; import java.util.Map; import java.util.UUID;

@Service public class TraceService {
 private static final Logger log=LoggerFactory.getLogger(TraceService.class); private final TracePersistenceService persistence; private final RedactionService redaction;
 public TraceService(TracePersistenceService p,RedactionService r){persistence=p;redaction=r;}
 public RootTrace startRootRun(Long sessionId,Long userId,Long inputEventId,String provider,String model,String promptVersion,Map<String,?> metadata){
  return startRootRun(sessionId,userId,inputEventId,provider,model,promptVersion,false,"sendMessage",metadata);
 }
 public RootTrace startDryRunRoot(Long sessionId,Long userId,String originalTraceId,String reason,String provider,Map<String,?> metadata){
  java.util.Map<String,Object> values=new java.util.LinkedHashMap<>();if(metadata!=null)values.putAll(metadata);values.put("originalTraceId",originalTraceId);values.put("reason",reason);values.put("providerMode",provider);
  return startRootRun(sessionId,userId,null,provider,"mock-agent","stage7b-dry-run",true,"diagnosticDryRun",values);
 }
 private RootTrace startRootRun(Long sessionId,Long userId,Long inputEventId,String provider,String model,String promptVersion,boolean dryRun,String spanName,Map<String,?> metadata){
  String traceId=id(); String rootSpanId=id(); LocalDateTime now=LocalDateTime.now();
  try { TraceRun run=new TraceRun();run.setTraceId(traceId);run.setSessionId(sessionId);run.setUserId(userId);run.setRootInputEventId(inputEventId);run.setStatus(TraceStatus.RUNNING.name());run.setProvider(provider);run.setModel(model);run.setPromptVersion(promptVersion);run.setDryRun(dryRun);run.setStartedAt(now);run.setMetadataJson(redaction.redactObject(metadata).value());persistence.saveRun(run);
   TraceSpan span=new TraceSpan();span.setSpanId(rootSpanId);span.setTraceId(traceId);span.setSpanType(SpanType.REQUEST.name());span.setName(spanName);span.setStatus(TraceStatus.RUNNING.name());span.setStartedAt(now);span.setInputRef(inputEventId==null?null:"SESSION_EVENT:"+inputEventId);span.setMetadataJson("{}");persistence.saveSpan(span);return new RootTrace(traceId,rootSpanId,true);
  } catch(RuntimeException ex){log.warn("Trace root creation failed for session {}: {}",sessionId,redaction.redact(ex.getMessage()).value());return RootTrace.unavailable();}
 }
 public SpanHandle startSpan(SpanType type,String name,Map<String,?> metadata){TraceContextHolder.TraceContext c=TraceContextHolder.current();return c==null?SpanHandle.unavailable():startSpan(c.traceId(),c.spanId(),type,name,metadata);}
 public SpanHandle startSpan(String traceId,String parentSpanId,SpanType type,String name,Map<String,?> metadata){if(traceId==null)return SpanHandle.unavailable();TraceSpan s=new TraceSpan();s.setSpanId(id());s.setTraceId(traceId);s.setParentSpanId(parentSpanId);s.setSpanType(type.name());s.setName(name);s.setStatus(TraceStatus.RUNNING.name());s.setStartedAt(LocalDateTime.now());s.setMetadataJson(redaction.redactObject(metadata).value());try{persistence.saveSpan(s);recordEvent(traceId,s.getSpanId(),TraceEventType.STARTED,name,Map.of());return new SpanHandle(traceId,s.getSpanId(),true);}catch(RuntimeException ex){warn("start span",ex);return SpanHandle.unavailable();}}
 public void finishRootRunSuccess(String traceId,Long workflowId,Long outputEventId,Map<String,?> metadata){if(traceId==null)return;try{TraceRun r=findRun(traceId);r.setWorkflowId(workflowId);r.setRootOutputEventId(outputEventId);finishRun(r,TraceStatus.SUCCEEDED,null,null);persistence.saveRun(r);finishRequestSpan(traceId,true,null,null);recordSnapshot(traceId,null,"FINAL_OUTPUT","SESSION_EVENT",String.valueOf(outputEventId),metadata);}catch(RuntimeException ex){warn("finish root",ex);}}
 public void finishRootRunFailure(String traceId,String code,Throwable error){if(traceId==null)return;try{TraceRun r=findRun(traceId);finishRun(r,TraceStatus.FAILED,code,error==null?null:error.getMessage());persistence.saveRun(r);finishRequestSpan(traceId,false,code,error);}catch(RuntimeException ex){warn("fail root",ex);}}
 public void finishSpanSuccess(SpanHandle h,String outputRef,Map<String,?> metadata){finishSpan(h,TraceStatus.SUCCEEDED,outputRef,null,null,metadata);}
 public void finishSpanFailure(SpanHandle h,String code,Throwable error,Map<String,?> metadata){finishSpan(h,TraceStatus.FAILED,null,code,error==null?null:error.getMessage(),metadata);}
 private void finishSpan(SpanHandle h,TraceStatus status,String outputRef,String code,String message,Map<String,?> metadata){if(h==null||!h.available())return;try{TraceSpan s=findSpan(h.spanId());s.setStatus(status.name());s.setOutputRef(outputRef);s.setErrorCode(code);s.setErrorMessage(limit(redaction.redact(message).value()));s.setMetadataJson(redaction.redactObject(metadata).value());s.setFinishedAt(LocalDateTime.now());s.setDurationMs(Math.max(0,Duration.between(s.getStartedAt(),s.getFinishedAt()).toMillis()));persistence.saveSpan(s);recordEvent(h.traceId(),h.spanId(),status==TraceStatus.SUCCEEDED?TraceEventType.SUCCEEDED:TraceEventType.FAILED,s.getName(),metadata);}catch(RuntimeException ex){warn("finish span",ex);}}
 public void recordEvent(String traceId,String spanId,TraceEventType type,String name,Map<String,?> metadata){if(traceId==null)return;try{TraceEvent e=new TraceEvent();e.setTraceId(traceId);e.setSpanId(spanId);e.setEventType(type.name());e.setName(name);e.setMetadataJson(redaction.redactObject(metadata).value());e.setOccurredAt(LocalDateTime.now());persistence.saveEvent(e);}catch(RuntimeException ex){warn("record event",ex);}}
 public void recordSnapshot(String traceId,String spanId,String type,String refType,String refId,Object payload){if(traceId==null)return;try{var rr=redaction.redactObject(payload);TraceSnapshot s=new TraceSnapshot();s.setTraceId(traceId);s.setSpanId(spanId);s.setSnapshotType(type);s.setRefType(refType);s.setRefId(refId);s.setPayloadJson(rr.value());s.setPayloadHash(hash(rr.value()));s.setRedactionSummaryJson("{\"redactedCount\":"+rr.redactedCount()+"}");s.setCreatedAt(LocalDateTime.now());persistence.saveSnapshot(s);if(rr.redactedCount()>0)recordEvent(traceId,spanId,TraceEventType.REDACTED,"snapshot-redacted",Map.of("count",rr.redactedCount()));}catch(RuntimeException ex){warn("record snapshot",ex);}}
 public void recordCurrentSnapshot(TraceSnapshotType type,String refType,String refId,Object payload){TraceContextHolder.TraceContext c=TraceContextHolder.current();if(c!=null)recordSnapshot(c.traceId(),c.spanId(),type.name(),refType,refId,payload);}
 public void linkExistingRecord(String traceId,String spanId,String type,Object id){recordSnapshot(traceId,spanId,"LINK",type,String.valueOf(id),Map.of("refType",type,"refId",String.valueOf(id)));}
 private TraceRun findRun(String id){return persistence.findRun(id);}
 private TraceSpan findSpan(String id){return persistence.findSpan(id);}
 private void finishRequestSpan(String traceId,boolean success,String code,Throwable error){persistence.findSpans(traceId).stream().filter(s->SpanType.REQUEST.name().equals(s.getSpanType())&&s.getParentSpanId()==null).findFirst().ifPresent(s->{SpanHandle h=new SpanHandle(traceId,s.getSpanId(),true);if(success)finishSpanSuccess(h,null,Map.of());else finishSpanFailure(h,code,error,Map.of());});}
 private void finishRun(TraceRun r,TraceStatus s,String code,String msg){r.setStatus(s.name());r.setFinishedAt(LocalDateTime.now());r.setDurationMs(Math.max(0,Duration.between(r.getStartedAt(),r.getFinishedAt()).toMillis()));r.setErrorCode(code);r.setErrorMessage(limit(redaction.redact(msg).value()));}
 private void warn(String op,RuntimeException ex){log.warn("Trace {} failed: {}",op,redaction.redact(ex.getMessage()).value());}
 private static String id(){return UUID.randomUUID().toString().replace("-","");} private static String limit(String v){return v==null?null:v.substring(0,Math.min(v.length(),512));} private static String hash(String v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest((v==null?"":v).getBytes(StandardCharsets.UTF_8)));}catch(Exception e){return null;}}
 public record RootTrace(String traceId,String rootSpanId,boolean available){public static RootTrace unavailable(){return new RootTrace(null,null,false);}}
 public record SpanHandle(String traceId,String spanId,boolean available){public static SpanHandle unavailable(){return new SpanHandle(null,null,false);}}
}
