package travelcare_agent.trace;

public enum TraceEventType {
    STARTED, SUCCEEDED, FAILED, TIMEOUT, FALLBACK, RETRY, GUARDRAIL_BLOCKED,
    HANDOFF_REQUIRED, CACHE_HIT, IDEMPOTENCY_REUSED, REDACTED, DRY_RUN_SKIPPED_SIDE_EFFECT,
    ANSWERABILITY_PASSED, ANSWERABILITY_BLOCKED, ANSWERABILITY_PARTIAL,
    CITATION_VALIDATED, CITATION_REJECTED
}
