package travelcare_agent.trace;

public enum TraceSnapshotType {
    USER_INPUT,
    CONTEXT_SUMMARY,
    RETRIEVAL_SUMMARY,
    MODEL_INPUT,
    MODEL_OUTPUT,
    MODEL_SAFETY_DECISION,
    TOOL_REQUEST,
    TOOL_RESULT,
    POLICY_INPUT,
    POLICY_DECISION,
    ANSWERABILITY_INPUT,
    ANSWERABILITY_DECISION,
    CITATION_SUMMARY,
    WORKFLOW_PATH,
    FINAL_OUTPUT
}
